development:
  secret_key_base: d10573fdacd84e6fb237f5b0b5512833938a7c6868721a58c21922ab05ddc1c9372453d0bfc0886b037e054653cf84bdd02edd54d2e09fead7499f81774f865a

test:
  secret_key_base: 2178cc9e12657b4b4038c181276a22fadf81fa1db793e5a00b507966817b720c68102a519162290d3423fbc87d02c57eb3a90fab2f962aa6aebd7b479fc4dd3d

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
